# Global markdownlint configuration
# Symlinked to ~/.markdownlint-cli2.yaml via stow

config:
  # MD013 - Line length
  # Disabled: Using prettier with --print-width=120 for line wrapping
  MD013: false

  # MD033 - Inline HTML
  # Allow HTML in markdown (useful for details/summary, etc.)
  MD033: false

  # MD041 - First line should be a heading
  # Disabled: Files may start with frontmatter
  MD041: false

  # MD024 - Multiple headings with same content
  # Allow duplicate headings in different sections
  MD024:
    siblings_only: true

  # MD026 - Trailing punctuation in heading
  # Allow question marks in headings
  MD026:
    punctuation: ".,;:!"

  # MD036 - Emphasis used instead of heading
  # Disabled: Sometimes emphasis is intentional
  MD036: false

  # MD046 - Code block style
  # Prefer fenced code blocks
  MD046:
    style: fenced

  # MD048 - Code fence style
  # Use backticks for fences
  MD048:
    style: backtick

  # MD049 - Emphasis style
  # Use asterisks for emphasis
  MD049:
    style: asterisk

  # MD050 - Strong style
  # Use asterisks for strong
  MD050:
    style: asterisk
